christian@christian-desktop:~/testMavlink$ python3 mavControlTel2.py
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1721776495.798573    2910 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache
I0000 00:00:1721776496.024131    2913 subchannel.cc:806] subchannel 0xffff54001330 {address=ipv6:%5B::1%5D:50051, args={grpc.client_channel_factory=0xaaaae4157730, grpc.default_authority=localhost:50051, grpc.internal.channel_credentials=0xaaaae40241b0, grpc.internal.client_channel_call_destination=0xffff8831edc8, grpc.internal.event_engine=0xffff540136b0, grpc.internal.security_connector=0xffff54014320, grpc.internal.subchannel_pool=0xaaaae40f53d0, grpc.primary_user_agent=grpc-python/1.65.1, grpc.resource_quota=0xaaaae40221f0, grpc.server_uri=dns:///localhost:50051}}: connect failed (UNKNOWN:Failed to connect to remote host: connect: Connection refused (111) {created_time:"2024-07-23T17:14:56.01817772-06:00"}), backing off for 993 ms
I0000 00:00:1721776496.025126    2913 subchannel.cc:806] subchannel 0xffff54001f40 {address=ipv4:127.0.0.1:50051, args={grpc.client_channel_factory=0xaaaae4157730, grpc.default_authority=localhost:50051, grpc.internal.channel_credentials=0xaaaae40241b0, grpc.internal.client_channel_call_destination=0xffff8831edc8, grpc.internal.event_engine=0xffff54001a70, grpc.internal.security_connector=0xffff54001b70, grpc.internal.subchannel_pool=0xaaaae40f53d0, grpc.primary_user_agent=grpc-python/1.65.1, grpc.resource_quota=0xaaaae40221f0, grpc.server_uri=dns:///localhost:50051}}: connect failed (UNKNOWN:Failed to connect to remote host: connect: Connection refused (111) {created_time:"2024-07-23T17:14:56.024913777-06:00"}), backing off for 999 ms
I0000 00:00:1721776497.018805    2918 subchannel.cc:761] subchannel 0xffff54001330 {address=ipv6:%5B::1%5D:50051, args={grpc.client_channel_factory=0xaaaae4157730, grpc.default_authority=localhost:50051, grpc.internal.channel_credentials=0xaaaae40241b0, grpc.internal.client_channel_call_destination=0xffff8831edc8, grpc.internal.event_engine=0xffff540136b0, grpc.internal.security_connector=0xffff54014320, grpc.internal.subchannel_pool=0xaaaae40f53d0, grpc.primary_user_agent=grpc-python/1.65.1, grpc.resource_quota=0xaaaae40221f0, grpc.server_uri=dns:///localhost:50051}}: backoff delay elapsed, reporting IDLE
I0000 00:00:1721776497.020387    2913 subchannel.cc:806] subchannel 0xffff54001330 {address=ipv6:%5B::1%5D:50051, args={grpc.client_channel_factory=0xaaaae4157730, grpc.default_authority=localhost:50051, grpc.internal.channel_credentials=0xaaaae40241b0, grpc.internal.client_channel_call_destination=0xffff8831edc8, grpc.internal.event_engine=0xffff540136b0, grpc.internal.security_connector=0xffff54014320, grpc.internal.subchannel_pool=0xaaaae40f53d0, grpc.primary_user_agent=grpc-python/1.65.1, grpc.resource_quota=0xaaaae40221f0, grpc.server_uri=dns:///localhost:50051}}: connect failed (UNKNOWN:Failed to connect to remote host: connect: Connection refused (111) {created_time:"2024-07-23T17:14:57.019951875-06:00"}), backing off for 1543 ms
I0000 00:00:1721776497.025812    2917 subchannel.cc:761] subchannel 0xffff54001f40 {address=ipv4:127.0.0.1:50051, args={grpc.client_channel_factory=0xaaaae4157730, grpc.default_authority=localhost:50051, grpc.internal.channel_credentials=0xaaaae40241b0, grpc.internal.client_channel_call_destination=0xffff8831edc8, grpc.internal.event_engine=0xffff54001a70, grpc.internal.security_connector=0xffff54001b70, grpc.internal.subchannel_pool=0xaaaae40f53d0, grpc.primary_user_agent=grpc-python/1.65.1, grpc.resource_quota=0xaaaae40221f0, grpc.server_uri=dns:///localhost:50051}}: backoff delay elapsed, reporting IDLE
I0000 00:00:1721776497.026926    2913 subchannel.cc:806] subchannel 0xffff54001f40 {address=ipv4:127.0.0.1:50051, args={grpc.client_channel_factory=0xaaaae4157730, grpc.default_authority=localhost:50051, grpc.internal.channel_credentials=0xaaaae40241b0, grpc.internal.client_channel_call_destination=0xffff8831edc8, grpc.internal.event_engine=0xffff54001a70, grpc.internal.security_connector=0xffff54001b70, grpc.internal.subchannel_pool=0xaaaae40f53d0, grpc.primary_user_agent=grpc-python/1.65.1, grpc.resource_quota=0xaaaae40221f0, grpc.server_uri=dns:///localhost:50051}}: connect failed (UNKNOWN:Failed to connect to remote host: connect: Connection refused (111) {created_time:"2024-07-23T17:14:57.026615563-06:00"}), backing off for 1760 ms
I0000 00:00:1721776498.564471    2917 subchannel.cc:761] subchannel 0xffff54001330 {address=ipv6:%5B::1%5D:50051, args={grpc.client_channel_factory=0xaaaae4157730, grpc.default_authority=localhost:50051, grpc.internal.channel_credentials=0xaaaae40241b0, grpc.internal.client_channel_call_destination=0xffff8831edc8, grpc.internal.event_engine=0xffff540136b0, grpc.internal.security_connector=0xffff54014320, grpc.internal.subchannel_pool=0xaaaae40f53d0, grpc.primary_user_agent=grpc-python/1.65.1, grpc.resource_quota=0xaaaae40221f0, grpc.server_uri=dns:///localhost:50051}}: backoff delay elapsed, reporting IDLE
Waiting for drone to connect...
Drone connected!
Sending proof of life signal
Unexpected error: local variable 'thrust' referenced before assignment
Traceback (most recent call last):
  File "/home/christian/testMavlink/mavControlTel2.py", line 79, in <module>
    asyncio.run(run())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/christian/testMavlink/mavControlTel2.py", line 76, in run
    await asyncio.gather(control_task, sensor_task, thrust_task)
  File "/home/christian/testMavlink/mavControlTel2.py", line 12, in send_proof_of_life
    await drone.offboard.set_actuator_control(ActuatorControl([0.0] * 8))
  File "/usr/local/lib/python3.10/dist-packages/mavsdk/offboard.py", line 1255, in set_actuator_control
    actuator_control.translate_to_rpc(request.actuator_control)
  File "/usr/local/lib/python3.10/dist-packages/mavsdk/offboard.py", line 245, in translate_to_rpc
    elem.translate_to_rpc(rpc_elem)
AttributeError: 'float' object has no attribute 'translate_to_rpc'

